# Generated by Django 6.0.1 on 2026-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesrecettes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='estimated_cost',
            field=models.IntegerField(choices=[(1, 'FCFA - Économique'), (2, 'FCFA - Modéré'), (3, 'FCFA - Coûteux')], default=2),
        ),
    ]
