# Generated by Django 6.0.1 on 2026-01-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesrecettes', '0002_alter_recipe_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
