# Generated by Django 6.0.1 on 2026-01-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesrecettes', '0003_recipecategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'ordering': ['name']},
        ),
    ]
